package ch.fhnw.bscwi.gpm.loanapproval.service.client.processrequestservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.6
 * 2014-04-19T18:11:11.485+02:00
 * Generated source version: 2.6.6
 * 
 */
@WebServiceClient(name = "ProcessRequestServiceService", 
                  wsdlLocation = "http://localhost:8080/LoanApproval/ProcessRequestServiceService?WSDL",
                  targetNamespace = "http://service.loanapproval.gpm.bscwi.fhnw.ch/") 
public class ProcessRequestServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.loanapproval.gpm.bscwi.fhnw.ch/", "ProcessRequestServiceService");
    public final static QName ProcessRequestServicePort = new QName("http://service.loanapproval.gpm.bscwi.fhnw.ch/", "ProcessRequestServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/LoanApproval/ProcessRequestServiceService?WSDL");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ProcessRequestServiceService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/LoanApproval/ProcessRequestServiceService?WSDL");
        }
        WSDL_LOCATION = url;
    }

    public ProcessRequestServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ProcessRequestServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProcessRequestServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ProcessRequestServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ProcessRequestServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ProcessRequestServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ProcessRequestService
     */
    @WebEndpoint(name = "ProcessRequestServicePort")
    public ProcessRequestService getProcessRequestServicePort() {
        return super.getPort(ProcessRequestServicePort, ProcessRequestService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProcessRequestService
     */
    @WebEndpoint(name = "ProcessRequestServicePort")
    public ProcessRequestService getProcessRequestServicePort(WebServiceFeature... features) {
        return super.getPort(ProcessRequestServicePort, ProcessRequestService.class, features);
    }

}
