package ch.fhnw.bscwi.gpm.loanapproval.service.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.6
 * 2014-04-19T19:06:50.366+02:00
 * Generated source version: 2.6.6
 * 
 */
@WebServiceClient(name = "LoanApprovalESBService", 
                  wsdlLocation = "http://localhost:9280/LoanApprovalESBService/LoanApprovalESBService?wsdl",
                  targetNamespace = "http://service.loanapproval.gpm.bscwi.fhnw.ch/") 
public class LoanApprovalESBService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.loanapproval.gpm.bscwi.fhnw.ch/", "LoanApprovalESBService");
    public final static QName LoanApprovalESBServiceSOAP = new QName("http://service.loanapproval.gpm.bscwi.fhnw.ch/", "LoanApprovalESBServiceSOAP");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:9280/LoanApprovalESBService/LoanApprovalESBService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(LoanApprovalESBService_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:9280/LoanApprovalESBService/LoanApprovalESBService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public LoanApprovalESBService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public LoanApprovalESBService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LoanApprovalESBService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public LoanApprovalESBService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public LoanApprovalESBService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public LoanApprovalESBService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns LoanApprovalESBService
     */
    @WebEndpoint(name = "LoanApprovalESBServiceSOAP")
    public LoanApprovalESBService getLoanApprovalESBServiceSOAP() {
        return super.getPort(LoanApprovalESBServiceSOAP, LoanApprovalESBService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LoanApprovalESBService
     */
    @WebEndpoint(name = "LoanApprovalESBServiceSOAP")
    public LoanApprovalESBService getLoanApprovalESBServiceSOAP(WebServiceFeature... features) {
        return super.getPort(LoanApprovalESBServiceSOAP, LoanApprovalESBService.class, features);
    }

}
