package ch.fhnw.bscwi.gpm.loanapproval.service.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.6
 * 2014-04-19T19:06:50.319+02:00
 * Generated source version: 2.6.6
 * 
 */
@WebService(targetNamespace = "http://service.loanapproval.gpm.bscwi.fhnw.ch/", name = "LoanApprovalESBService")
@XmlSeeAlso({ObjectFactory.class})
public interface LoanApprovalESBService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "loadCustomer", targetNamespace = "http://service.loanapproval.gpm.bscwi.fhnw.ch/", className = "ch.fhnw.bscwi.gpm.loanapproval.service.client.LoadCustomer")
    @WebMethod
    @ResponseWrapper(localName = "loadCustomerResponse", targetNamespace = "http://service.loanapproval.gpm.bscwi.fhnw.ch/", className = "ch.fhnw.bscwi.gpm.loanapproval.service.client.LoadCustomerResponse")
    public ch.fhnw.bscwi.gpm.loanapproval.service.client.CustomerDTO loadCustomer(
        @WebParam(name = "customerId", targetNamespace = "")
        java.lang.Long customerId
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "processRequest", targetNamespace = "http://service.loanapproval.gpm.bscwi.fhnw.ch/", className = "ch.fhnw.bscwi.gpm.loanapproval.service.client.ProcessRequest")
    @WebMethod
    @ResponseWrapper(localName = "processRequestResponse", targetNamespace = "http://service.loanapproval.gpm.bscwi.fhnw.ch/", className = "ch.fhnw.bscwi.gpm.loanapproval.service.client.ProcessRequestResponse")
    public boolean processRequest(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Long arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.Long arg1
    );
}
